 family.load([
            {
                "id": 1,
                "pids": [2, 0],
                "name": "King George VI",
                "img": "https://giapha.kennatech.vn//storage/users/businessman.png",
                "gender": 'male',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, 
            {
                "id": 2,
                "pids": [1],
                "name": "Queen Elizabeth",
                "title": "The Queen Mother",
                "img": "https://giapha.kennatech.vn//storage/users/human.png",
                "gender": 'female',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 3,
                "pids": [4],
                "mid": 2,
                "fid": 1,
                "name": "Queen Elizabeth II",
                "img": "https://giapha.kennatech.vn//storage/users/human.png",
                "gender": 'female',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 4,
                "pids": [3],
                "name": "Prince Philip",
                "title": "Duke of Edinburgh",
                "img": "https://giapha.kennatech.vn//storage/users/businessman.png",
                "gender": 'male',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 5,
                "mid": 2,
                "fid": 1,
                "name": "Princess Margaret",
                "img": "https://giapha.kennatech.vn//storage/users/businessman.png",
                "gender": 'male',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 6,
                "mid": 3,
                "fid": 4,
                "pids": [7, 8],
                "name": "Charles",
                "title": "Prince of Wales",
                "img": "https://giapha.kennatech.vn//storage/users/businessman.png",
                "gender": 'male',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 7,
                "pids": [6],
                "name": "Diana",
                "title": "Princess of Wales",
                "img": "https://giapha.kennatech.vn//storage/users/human.png",
                "gender": 'female',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 8,
                "pids": [6],
                "name": "Camila",
                "title": "Duchess of Cornwall",
                "img": "https://giapha.kennatech.vn//storage/users/human.png",
                "gender": 'female',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 9,
                "mid": 3,
                "fid": 4,
                "name": "Anne",
                "title": "Princess Royal",
                "img": "https://giapha.kennatech.vn//storage/users/human.png",
                "gender": 'female',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 10,
                "mid": 3,
                "fid": 4,
                "name": "Prince Andrew",
                "title": "Duke of York",
                "img": "https://giapha.kennatech.vn//storage/users/businessman.png",
                "gender": 'male',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 11,
                "mid": 3,
                "fid": 4,
                "name": "Prince Edward",
                "title": "Earl of Wessex",
                "img": "https://giapha.kennatech.vn//storage/users/businessman.png",
                "gender": 'male',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 12,
                "fid": 6,
                "mid": 7,
                "pids": [14],
                "name": "Prince William",
                "title": "Duch of Cambridge",
                "img": "https://giapha.kennatech.vn//storage/users/businessman.png",
                "gender": 'male',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 13,
                "fid": 6,
                "mid": 7,
                "pids": [15],
                "name": "Prince Harry",
                "img": "https://giapha.kennatech.vn//storage/users/businessman.png",
                "gender": 'male',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 14,
                "pids": [12],
                "name": "Catherine",
                "title": "Duchess of Cambridge",
                "img": "https://giapha.kennatech.vn//storage/users/human.png",
                "gender": 'female',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 15,
                "pids": [13],
                "name": "Meghan Markle",
                "img": "https://giapha.kennatech.vn//storage/users/human.png",
                "gender": 'female',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 16,
                "fid": 12,
                "mid": 14,
                "name": "Prince George",
                "img": "https://giapha.kennatech.vn//storage/users/businessman.png",
                "gender": 'male',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 17,
                "fid": 12,
                "mid": 14,
                "name": "Prince Charlotte",
                "img": "https://giapha.kennatech.vn//storage/users/human.png",
                "gender": 'female',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }, {
                "id": 18,
                "fid": 12,
                "mid": 14,
                "name": "Prince Louis",
                "img": "https://giapha.kennatech.vn//storage/users/businessman.png",
                "gender": 'male',
                "date_of_birth": '',
                "date_of_death": '',
                "status": '',
                "address_old": '',
                "address": '',
                "level": '',
                "job": ''
            }
        ]);